job: Test
  runs-on:
    - runs-on runs-on=${{ github.run_id }}# required so that RunsOn knows it needs to process the workflow
    - cpu=4
    - ram=16
    - family=m7a+m7i-flex
    - image=ubuntu22-full-x64
